### PR TITLE
Fix some e2e tests

### PR DESCRIPTION
**Pull request by villfa**
Feel free to cherrypick the commits you want

### CODE REVIEW

**Comment by villfa** [comment]
The error of `e2e_027 - 8.0` is interesting:
```
composer --working-dir=build/set027-laravel dump-autoload --no-dev
Generating optimized autoload files
Class Illuminate\Foundation\ComposerScripts is not autoloadable, can not call post-autoload-dump script
> @php artisan package:discover
PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /home/runner/work/php-scoper/php-scoper/build/set027-laravel/vendor/nesbot/carbon/src/Carbon/CarbonInterval.php on line 1394

In CarbonInterval.php line 1394:
                                                                               
  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b :   
  c) ? d : e` or `a ? b : (c ? d : e)`                                         
                                                                               

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255
Makefile:342: recipe for target 'e2e_027' failed
make: *** [e2e_027] Error 255
```

Here the line in cause:
```php
    public function invert($inverted = null)
    {
        $this->invert = \func_num_args() === 0 ? !$this->invert : $inverted ? 1 : 0;
        return $this;
    }
```

and here the original function before being scoped:
```php
    public function invert($inverted = null)
    {
        $this->invert = (\func_num_args() === 0 ? !$this->invert : $inverted) ? 1 : 0;

        return $this;
    }
```

I don't know how the parentheses have disappeared.

**Comment by smoench** [comment]
@villfa I opened a PR with a (failing) test case https://github.com/humbug/php-scoper/pull/447

**Comment by smoench** [comment]
@villfa a new version of https://github.com/nikic/PHP-Parser/releases/tag/v4.10.3 has been just released fixing your issue :-)

**Comment by villfa** [comment]
Finally it's green!

**Pull request closed without merging**
